# version: 2.1
# jobs:
#   hello-job:
#     machine:
#       image: ubuntu-2204:2022.07.1
#     steps: 
#     - checkout # check out the code in the project directory # check out the code in the project directory 
#     - run: echo "hello world" # run the `echo` command
# workflows:
#   my-workflow:
#     jobs: 
#       - hello-job

# # CircleCI configuration file
# version: 2.1
# jobs: 
#   # Job one with a unique name
#   say_hello:
#     docker:
#       - image: cimg/base:2022.05
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
#     steps: 
#       - run: echo "Say hello to YAML!" # Job two with a unique name
#   say_goodbye:
#     docker:
#       - image: cimg/base:2022.05
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
#     steps: 
#       - run: echo "Say goodbye to YAML!"
# workflows:
# # Name of workflow
#   hello_and_goodbye:
# # List of jobs that will run
#     jobs: 
#       - say_hello 
#       - say_goodbye

version: 2.1

orbs:
  node: circleci/node@5.0.3
  gh-pages: sugarshin/gh-pages@1.0.1

jobs:
  install-and-test:
    executor:
      name: node/default
      tag: '16.17'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
          name: Run npm tests
  deploy-github-pages:
    executor: gh-pages/default
    steps:
      - checkout
      - run: ./build.sh
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: <fingerprint>

workflows:
  test_and_deploy_my_app:
    jobs:
      - install-and-test
      -  deploy-github-pages