# version: 2.1
# jobs:
#   hello-job:
#     machine:
#       image: ubuntu-2204:2022.07.1
#     steps: 
#     - checkout # check out the code in the project directory # check out the code in the project directory 
#     - run: echo "hello world" # run the `echo` command
# workflows:
#   my-workflow:
#     jobs: 
#       - hello-job

# # CircleCI configuration file
# version: 2.1
# jobs: 
#   # Job one with a unique name
#   say_hello:
#     docker:
#       - image: cimg/base:2022.05
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
#     steps: 
#       - run: echo "Say hello to YAML!" # Job two with a unique name
#   say_goodbye:
#     docker:
#       - image: cimg/base:2022.05
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
#     steps: 
#       - run: echo "Say goodbye to YAML!"
# workflows:
# # Name of workflow
#   hello_and_goodbye:
# # List of jobs that will run
#     jobs: 
#       - say_hello 
#       - say_goodbye

version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  install-and-test:
    executor:
      name: node/default
      tag: '16.17'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
          name: Run npm tests
  deploy-github-pages:
    executor:
      name: node/default
      tag: '16.17'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build << pipeline.git.branch >>
          command: >
            npm i git &&\ 
            git config --global user.email "55555topkung@gmail.com" &&\ 
            git config --global user.name "TopThammanun" &&\
            npm install -g yarn &&\
            yarn install
      - run:
          name: deploy
          command: >
            git remote set-url origin \
            << pipeline.project.git_url >>.git &&\
            PUBLIC_URL=/react-deploy npm run deploy

workflows:
  test_and_deploy_my_app:
    jobs:
      - install-and-test
      -  deploy-github-pages